/**
 * Column + table definitions — one source of truth for "what does this mean?".
 *
 * A definition is consumed in three places:
 *   1. the GUI hover tooltip on table headers / field labels / entity cards,
 *   2. the assistant's schema context (so a good description improves the
 *      model's categorization + extraction), and
 *   3. the `set_definition` assistant tool (write-back).
 *
 * Resolution order: an operator-authored value (stored in
 * `_lattice_gui_column_meta.description` / `_lattice_gui_meta.description`) wins;
 * otherwise a built-in default (native entities + common system columns);
 * otherwise none (the caller falls back to the column's type/role).
 *
 * Definitions for user-created columns/tables are auto-generated by a cheap,
 * non-blocking, fail-silent Haiku pass at creation time (see the generators
 * below) — never overwriting an authored value.
 */
import type { Lattice } from '../lattice.js';
// Type-only import (erased at runtime) so this module stays a leaf — importing
// the runtime `DEFAULT_MODEL` from ai/chat would form a cycle once ai/dispatch
// imports this module for set_definition. The model const is inlined instead.
import type { LlmClient } from './ai/chat.js';
import { isNativeEntity } from '../framework/native-entities.js';

/** Cheapest capable model for the throwaway definition-generation passes. */
const GEN_MODEL = 'claude-haiku-4-5';

/** Built-in definitions for the user-facing native entities (files/notes/secrets). */
export const BUILTIN_COLUMN_DESCRIPTIONS: Readonly<
  Record<string, Readonly<Record<string, string>>>
> = {
  files: {
    original_name: 'Original filename as uploaded.',
    mime: 'MIME content type of the file (e.g. application/pdf).',
    size_bytes: 'File size in bytes.',
    sha256: 'SHA-256 content hash — the canonical identifier of the stored file.',
    blob_path: 'Relative path to the stored binary under the lattice data/blobs directory.',
    ref_kind: "How the file is stored: 'blob' (an owned copy), 'local_ref', or 'cloud_ref'.",
    ref_uri: 'Durable pointer to the data: absolute local path, remote URL, or s3://bucket/key.',
    ref_provider: "Resolver that fetches the data: 'fs', 'web', 'gdrive', or 's3'.",
    source_json: 'Provider-specific metadata (etag, availability, bucket/key/region…).',
    extraction_status: "State of text extraction for this file (e.g. 'extracted', 'pending').",
    extracted_text: 'Text pulled from the file contents — used for search and enrichment.',
    description: 'Short summary of what this file is (AI- or human-authored).',
    artifact_type:
      "Set to 'markdown' for an assistant-authored document artifact; otherwise empty.",
  },
  notes: {
    title: 'Short title of the note.',
    body: 'Free-form note body (markdown).',
    source_file_id: 'Id of the files row this note was derived from, if any.',
  },
  secrets: {
    name: 'Unique name/key the secret is looked up by.',
    kind: 'Category of the secret (e.g. api_key, token, password).',
    value: 'The secret value — stored encrypted at rest.',
    description: 'What this secret is for.',
  },
};

/** Definitions for the system columns shared by (almost) every entity. */
export const BUILTIN_SYSTEM_COLUMN_DESCRIPTIONS: Readonly<Record<string, string>> = {
  id: 'Primary key — the unique identifier of this row.',
  created_at: 'When this row was created.',
  updated_at: 'When this row was last updated.',
  deleted_at: 'When this row was soft-deleted (NULL while the row is active).',
};

/** Built-in definitions for the user-facing native entities themselves. */
export const BUILTIN_TABLE_DESCRIPTIONS: Readonly<Record<string, string>> = {
  files: 'Uploaded, ingested, or assistant-authored files and documents.',
  notes: 'Free-form knowledge notes with a title and markdown body.',
  secrets: 'Named secrets (API keys, tokens) stored encrypted at rest.',
};

/** Built-in description for a column, or undefined if there is none. */
export function builtinColumnDescription(table: string, column: string): string | undefined {
  return BUILTIN_COLUMN_DESCRIPTIONS[table]?.[column] ?? BUILTIN_SYSTEM_COLUMN_DESCRIPTIONS[column];
}

/** Built-in description for a table, or undefined if there is none. */
export function builtinTableDescription(table: string): string | undefined {
  return BUILTIN_TABLE_DESCRIPTIONS[table];
}

/**
 * Resolve a column's effective description: operator-authored value wins, else
 * the built-in default, else undefined. Blank authored value clears the override.
 */
export function resolveColumnDescription(
  table: string,
  column: string,
  authored?: string | null,
): string | undefined {
  const a = typeof authored === 'string' ? authored.trim() : '';
  if (a) return a;
  return builtinColumnDescription(table, column);
}

/** Resolve a table's effective description (authored wins, else built-in). */
export function resolveTableDescription(
  table: string,
  authored?: string | null,
): string | undefined {
  const a = typeof authored === 'string' ? authored.trim() : '';
  if (a) return a;
  return builtinTableDescription(table);
}

// ── Consolidated metadata upserts ──────────────────────────────────────────
// One find-or-insert path each for column meta + table meta, so the AI tool,
// the GUI PUT endpoints, and the auto-generators all write the same way.

/**
 * Find-or-insert `_lattice_gui_column_meta` for (table, column), applying only
 * the provided fields. A blank `description` clears it (stored NULL). Stamps
 * `updated_at`. No-op-safe: never throws on a missing meta table — the caller
 * decides whether absence matters.
 */
export async function upsertColumnMeta(
  db: Lattice,
  table: string,
  column: string,
  patch: { description?: string | null; secret?: 0 | 1 },
): Promise<void> {
  const existing = (
    (await db.query('_lattice_gui_column_meta', {
      filters: [
        { col: 'table_name', op: 'eq', val: table },
        { col: 'column_name', op: 'eq', val: column },
      ],
    })) as { id: string }[]
  )[0];
  const fields: Record<string, unknown> = { updated_at: new Date().toISOString() };
  if (patch.description !== undefined) {
    const d = typeof patch.description === 'string' ? patch.description.trim() : '';
    fields.description = d ? d : null;
  }
  if (patch.secret !== undefined) fields.secret = patch.secret;
  if (existing) {
    await db.update('_lattice_gui_column_meta', existing.id, fields);
  } else {
    await db.insert('_lattice_gui_column_meta', {
      id: crypto.randomUUID(),
      table_name: table,
      column_name: column,
      secret: 0,
      ...fields,
    });
  }
}

/**
 * Find-or-insert `_lattice_gui_meta` for a table (PK = entity_name), applying
 * only the provided fields. Blank `description` clears it. Stamps `updated_at`.
 */
export async function upsertTableMeta(
  db: Lattice,
  table: string,
  patch: { description?: string | null; icon?: string | null },
): Promise<void> {
  const existing = (await db.get('_lattice_gui_meta', table)) as { entity_name: string } | null;
  const fields: Record<string, unknown> = { updated_at: new Date().toISOString() };
  if (patch.description !== undefined) {
    const d = typeof patch.description === 'string' ? patch.description.trim() : '';
    fields.description = d ? d : null;
  }
  if (patch.icon !== undefined) fields.icon = patch.icon;
  if (existing) {
    await db.update('_lattice_gui_meta', table, fields);
  } else {
    await db.insert('_lattice_gui_meta', { entity_name: table, ...fields });
  }
}

/** Authored (operator) column description, or undefined. Fail-silent. */
async function authoredColumnDescription(
  db: Lattice,
  table: string,
  column: string,
): Promise<string | undefined> {
  try {
    const row = (
      (await db.query('_lattice_gui_column_meta', {
        filters: [
          { col: 'table_name', op: 'eq', val: table },
          { col: 'column_name', op: 'eq', val: column },
        ],
      })) as { description?: string | null }[]
    )[0];
    const d = typeof row?.description === 'string' ? row.description.trim() : '';
    return d || undefined;
  } catch {
    return undefined;
  }
}

const SYSTEM_COL_RE = /^(id|.*_at|deleted_at)$/;

function isMetaTable(table: string): boolean {
  return table.startsWith('_lattice_') || table.startsWith('__lattice_');
}

// ── Auto-generation (cheap, non-blocking, fail-silent) ──────────────────────

/**
 * Generate one-line definitions for newly-added USER columns and store them.
 * One batched Haiku call per add-event. No-op when `client` is null. Skips
 * native entities, meta/system tables, system columns, columns that already
 * have a built-in default, and columns with an authored value (re-checked right
 * before the write — late-write guard). Never throws.
 */
export async function generateAndStoreColumnDescriptions(
  db: Lattice,
  table: string,
  columns: readonly string[],
  client: LlmClient | null,
): Promise<void> {
  if (!client) return;
  if (isNativeEntity(table) || isMetaTable(table)) return;
  try {
    const candidates: string[] = [];
    for (const col of columns) {
      if (SYSTEM_COL_RE.test(col)) continue;
      if (builtinColumnDescription(table, col)) continue;
      if (await authoredColumnDescription(db, table, col)) continue;
      candidates.push(col);
    }
    if (candidates.length === 0) return;

    // A couple of sample values per candidate column, to ground the definition.
    let samples = '';
    try {
      const rows = (await db.query(table, { limit: 3 })) as Record<string, unknown>[];
      samples = candidates
        .map((c) => {
          const vals = rows
            .map((r) => r[c])
            .filter((v) => v != null && v !== '')
            .slice(0, 2)
            .map((v) => String(v).slice(0, 40));
          return vals.length ? `  ${c}: ${vals.join(' | ')}` : `  ${c}: (no sample)`;
        })
        .join('\n');
    } catch {
      samples = candidates.map((c) => `  ${c}`).join('\n');
    }

    const prompt =
      `Table "${table}" has new columns. Write a concise one-line definition for each ` +
      `(what the column holds, plain language, no preamble).\n\nColumns + sample values:\n${samples}\n\n` +
      `Respond with ONLY a JSON object mapping each column name to its one-line definition.`;
    const turn = await client.runTurn({
      model: GEN_MODEL,
      system:
        'You document database columns. Reply with a compact JSON object {column: definition}. ' +
        'Each definition is a single plain sentence. No markdown, no commentary.',
      messages: [{ role: 'user', content: prompt }],
      tools: [],
      onText: () => undefined,
    });
    const defs = parseDefsJson(turn.text);
    for (const col of candidates) {
      const def = defs[col];
      if (!def || typeof def !== 'string') continue;
      // Late-write guard: don't clobber an authored value written meanwhile.
      if (await authoredColumnDescription(db, table, col)) continue;
      await upsertColumnMeta(db, table, col, { description: def.trim().slice(0, 280) });
    }
  } catch {
    /* fail-silent: a definition is a nicety, never block the write */
  }
}

/**
 * Generate + store a one-line definition for a newly-created USER table.
 * No-op when `client` is null; skips native/meta/junction tables and tables that
 * already have a built-in or authored description. Never throws.
 */
export async function generateAndStoreTableDescription(
  db: Lattice,
  table: string,
  columns: readonly string[],
  client: LlmClient | null,
): Promise<void> {
  if (!client) return;
  if (isNativeEntity(table) || isMetaTable(table) || builtinTableDescription(table)) return;
  try {
    const existing = (await db.get('_lattice_gui_meta', table)) as {
      description?: string | null;
    } | null;
    if (typeof existing?.description === 'string' && existing.description.trim()) return;
    const cols = columns
      .filter((c) => !SYSTEM_COL_RE.test(c))
      .slice(0, 24)
      .join(', ');
    const turn = await client.runTurn({
      model: GEN_MODEL,
      system:
        'You document database tables. Reply with a single plain sentence describing what the ' +
        'table stores. No markdown, no preamble, no quotes.',
      messages: [
        {
          role: 'user',
          content: `Table "${table}" with columns: ${cols || '(none)'}. One-line definition?`,
        },
      ],
      tools: [],
      onText: () => undefined,
    });
    const desc = turn.text
      .trim()
      .replace(/^["']|["']$/g, '')
      .slice(0, 280);
    if (!desc) return;
    const still = (await db.get('_lattice_gui_meta', table)) as {
      description?: string | null;
    } | null;
    if (typeof still?.description === 'string' && still.description.trim()) return;
    await upsertTableMeta(db, table, { description: desc });
  } catch {
    /* fail-silent */
  }
}

/** Best-effort parse of a `{column: definition}` JSON object from model text. */
function parseDefsJson(text: string): Record<string, string> {
  try {
    const start = text.indexOf('{');
    const end = text.lastIndexOf('}');
    if (start < 0 || end <= start) return {};
    const obj = JSON.parse(text.slice(start, end + 1)) as Record<string, unknown>;
    const out: Record<string, string> = {};
    for (const [k, v] of Object.entries(obj)) if (typeof v === 'string') out[k] = v;
    return out;
  } catch {
    return {};
  }
}
