/**
 * Options for {@link createReadOnlyHeader}.
 */
export interface ReadOnlyHeaderOptions {
  /** Name shown as the generator (default: `"Lattice"`). */
  generator?: string;
  /** Where to find the SESSION.md format spec (default: `"the Lattice documentation"`). */
  docsRef?: string;
}

/**
 * Build a read-only header for Lattice-generated context files.
 *
 * The header tells consumers (human or LLM) that the file is auto-generated
 * and that writes should go through SESSION.md instead.
 */
export function createReadOnlyHeader(options?: ReadOnlyHeaderOptions): string {
  const generator = options?.generator ?? 'Lattice';
  const docsRef = options?.docsRef ?? 'the Lattice documentation';
  return `<!-- READ ONLY — generated by ${generator}. Do not edit directly.
     To update data in Lattice: write entries to SESSION.md in this directory.
     Format: type: write | op: create/update/delete | table: <name> | target: <id>
     See ${docsRef} for the SESSION.md format spec. -->

`;
}

/**
 * Default read-only header prepended to all Lattice-generated context files.
 *
 * For a customised header, use {@link createReadOnlyHeader} instead.
 */
export const READ_ONLY_HEADER = createReadOnlyHeader();
