/**
 * Read-only header prepended to all Lattice-generated context files.
 *
 * Directs agents to SESSION.md for writes rather than editing generated files
 * directly. Include at the top of every rendered markdown context file so
 * agents see it at the start of their context window.
 */
export const READ_ONLY_HEADER = `<!-- READ ONLY — generated by lattice-sync. Do not edit directly.
     To update data in Lattice: write entries to SESSION.md in this directory.
     Format: type: write | op: create/update/delete | table: <name> | target: <id>
     See agents/shared/SESSION-FORMAT.md for the full spec. -->

`;
