import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import type { LatticeConfig, LatticeEntityDef, LatticeFieldDef } from '../config/types.js';
import { fieldToSqliteBaseType } from '../config/parser.js';

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface GenerateOptions {
  /** Parsed lattice config */
  config: LatticeConfig;
  /** Directory the config file lives in (for resolving relative outputFiles) */
  configDir: string;
  /** Where to write generated TypeScript + SQL files */
  outDir: string;
  /** Also create empty scaffold files at each entity's outputFile path */
  scaffold?: boolean;
}

export interface GenerateResult {
  filesWritten: string[];
}

/**
 * Run all code generators: TypeScript interfaces, SQL migration, and
 * (optionally) empty scaffold render files.
 */
export function generateAll(opts: GenerateOptions): GenerateResult {
  const { config, configDir, outDir, scaffold } = opts;
  const filesWritten: string[] = [];

  mkdirSync(outDir, { recursive: true });
  mkdirSync(join(outDir, 'migrations'), { recursive: true });

  // 1. TypeScript interfaces
  const tsPath = join(outDir, 'types.ts');
  writeFileSync(tsPath, generateTypes(config), 'utf-8');
  filesWritten.push(tsPath);

  // 2. SQL migration (0001_initial.sql)
  const sqlPath = join(outDir, 'migrations', '0001_initial.sql');
  writeFileSync(sqlPath, generateMigration(config), 'utf-8');
  filesWritten.push(sqlPath);

  // 3. Scaffold render output files (only creates, never overwrites)
  if (scaffold) {
    for (const [, entityDef] of Object.entries(config.entities)) {
      const outPath = resolve(configDir, entityDef.outputFile);
      if (!existsSync(outPath)) {
        mkdirSync(dirname(outPath), { recursive: true });
        writeFileSync(outPath, '', 'utf-8');
        filesWritten.push(outPath);
      }
    }
  }

  return { filesWritten };
}

// ---------------------------------------------------------------------------
// TypeScript interface generator
// ---------------------------------------------------------------------------

/**
 * Generate TypeScript interface declarations for all entities.
 *
 * A field is required (non-optional) if it has `primaryKey: true` or
 * `required: true`; all other fields are optional.
 */
export function generateTypes(config: LatticeConfig): string {
  const lines: string[] = ['// Auto-generated by `lattice generate`. Do not edit manually.', ''];

  for (const [entityName, entityDef] of Object.entries(config.entities)) {
    const typeName = toPascalCase(entityName);
    lines.push(`export interface ${typeName} {`);

    for (const [fieldName, field] of Object.entries(entityDef.fields)) {
      const tsType = toTsType(field.type);
      const optional = !field.primaryKey && !field.required;
      const mark = optional ? '?' : '';
      const comment = field.ref ? `  // → ${field.ref}` : '';
      lines.push(`  ${fieldName}${mark}: ${tsType};${comment}`);
    }

    lines.push('}', '');
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// SQL migration generator
// ---------------------------------------------------------------------------

/**
 * Generate a CREATE TABLE IF NOT EXISTS migration for all entities.
 *
 * Column specs mirror what Lattice itself derives at runtime, so the
 * generated SQL can be used as a standalone migration without Lattice.
 */
export function generateMigration(config: LatticeConfig): string {
  const lines: string[] = ['-- Auto-generated by `lattice generate`. Do not edit manually.', ''];

  for (const [entityName, entityDef] of Object.entries(config.entities)) {
    lines.push(`CREATE TABLE IF NOT EXISTS "${entityName}" (`);

    const colDefs = entityColDefs(entityDef);
    lines.push(colDefs.map((c) => `  ${c}`).join(',\n'));
    lines.push(');', '');
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function entityColDefs(entity: LatticeEntityDef): string[] {
  return Object.entries(entity.fields).map(([fieldName, field]) => {
    const parts: string[] = [`"${fieldName}"`, fieldToSqliteBaseType(field.type)];
    if (field.primaryKey) parts.push('PRIMARY KEY');
    else if (field.required) parts.push('NOT NULL');
    if (field.default !== undefined) {
      const dv = field.default;
      parts.push(
        typeof dv === 'string' ? `DEFAULT '${dv.replace(/'/g, "''")}'` : `DEFAULT ${String(dv)}`,
      );
    }
    return parts.join(' ');
  });
}

function toTsType(type: LatticeFieldDef['type']): string {
  switch (type) {
    case 'uuid':
    case 'text':
    case 'datetime':
    case 'date':
      return 'string';
    case 'integer':
    case 'int':
    case 'real':
    case 'float':
      return 'number';
    case 'boolean':
    case 'bool':
      return 'boolean';
    case 'blob':
      return 'Buffer';
  }
}

function toPascalCase(s: string): string {
  return s.replace(/(^|[_-])([a-z])/g, (_, __, c: string) => c.toUpperCase());
}
