import { describe, it, expect } from 'vitest';
import { generateTypes, generateMigration } from '../../src/codegen/generate.js';
import type { LatticeConfig } from '../../src/config/types.js';

// ---------------------------------------------------------------------------
// Shared fixture config
// ---------------------------------------------------------------------------

const FIXTURE_CONFIG: LatticeConfig = {
  db: './data/app.db',
  entities: {
    user: {
      fields: {
        id: { type: 'uuid', primaryKey: true },
        name: { type: 'text', required: true },
        email: { type: 'text' },
        score: { type: 'integer', default: 0 },
      },
      render: 'default-table',
      outputFile: 'context/USERS.md',
    },
    ticket: {
      fields: {
        id: { type: 'uuid', primaryKey: true },
        title: { type: 'text', required: true },
        status: { type: 'text', default: 'open' },
        assignee_id: { type: 'uuid', ref: 'user' },
      },
      render: 'default-list',
      outputFile: 'context/TICKETS.md',
    },
  },
};

// ---------------------------------------------------------------------------
// generateTypes()
// ---------------------------------------------------------------------------

describe('generateTypes()', () => {
  it('produces a valid TypeScript file header', () => {
    const output = generateTypes(FIXTURE_CONFIG);
    expect(output).toContain('// Auto-generated by `lattice generate`');
  });

  it('generates an interface per entity using PascalCase names', () => {
    const output = generateTypes(FIXTURE_CONFIG);
    expect(output).toContain('export interface User {');
    expect(output).toContain('export interface Ticket {');
  });

  it('marks primaryKey field as required (no ?)', () => {
    const output = generateTypes(FIXTURE_CONFIG);
    // id must be required — no ? marker
    expect(output).toContain('  id: string;');
    expect(output).not.toContain('  id?: string;');
  });

  it('marks required field as required (no ?)', () => {
    const output = generateTypes(FIXTURE_CONFIG);
    expect(output).toMatch(/name: string;/);
  });

  it('marks optional fields with ?', () => {
    const output = generateTypes(FIXTURE_CONFIG);
    expect(output).toMatch(/email\?: string;/);
    expect(output).toMatch(/assignee_id\?: string;/);
  });

  it('maps integer type to number', () => {
    const output = generateTypes(FIXTURE_CONFIG);
    expect(output).toMatch(/score\?: number;/);
  });

  it('maps ref field with a relation comment', () => {
    const output = generateTypes(FIXTURE_CONFIG);
    expect(output).toContain('assignee_id?: string;  // → user');
  });

  it('maps all scalar types correctly', () => {
    const config: LatticeConfig = {
      db: './app.db',
      entities: {
        all_types: {
          fields: {
            a: { type: 'uuid' },
            b: { type: 'text' },
            c: { type: 'integer' },
            d: { type: 'int' },
            e: { type: 'real' },
            f: { type: 'float' },
            g: { type: 'boolean' },
            h: { type: 'bool' },
            i: { type: 'datetime' },
            j: { type: 'date' },
            k: { type: 'blob' },
          },
          render: 'default-list',
          outputFile: 'out.md',
        },
      },
    };
    const output = generateTypes(config);
    expect(output).toContain('a?: string;');
    expect(output).toContain('b?: string;');
    expect(output).toContain('c?: number;');
    expect(output).toContain('d?: number;');
    expect(output).toContain('e?: number;');
    expect(output).toContain('f?: number;');
    expect(output).toContain('g?: boolean;');
    expect(output).toContain('h?: boolean;');
    expect(output).toContain('i?: string;');
    expect(output).toContain('j?: string;');
    expect(output).toContain('k?: Buffer;');
  });

  it('converts snake_case entity name to PascalCase', () => {
    const config: LatticeConfig = {
      db: './app.db',
      entities: {
        task_comment: {
          fields: { id: { type: 'uuid', primaryKey: true } },
          render: 'default-list',
          outputFile: 'out.md',
        },
      },
    };
    expect(generateTypes(config)).toContain('export interface TaskComment {');
  });

  it('generates interfaces for all entities in config', () => {
    const output = generateTypes(FIXTURE_CONFIG);
    expect(/^export interface /m.test(output)).toBe(true);
    const matches = [...output.matchAll(/^export interface \w+/gm)];
    expect(matches).toHaveLength(2);
  });
});

// ---------------------------------------------------------------------------
// generateMigration()
// ---------------------------------------------------------------------------

describe('generateMigration()', () => {
  it('produces a valid SQL file header', () => {
    const output = generateMigration(FIXTURE_CONFIG);
    expect(output).toContain('-- Auto-generated by `lattice generate`');
  });

  it('generates CREATE TABLE IF NOT EXISTS per entity', () => {
    const output = generateMigration(FIXTURE_CONFIG);
    expect(output).toContain('CREATE TABLE IF NOT EXISTS "user"');
    expect(output).toContain('CREATE TABLE IF NOT EXISTS "ticket"');
  });

  it('generates TEXT PRIMARY KEY for uuid primaryKey field', () => {
    const output = generateMigration(FIXTURE_CONFIG);
    expect(output).toContain('"id" TEXT PRIMARY KEY');
  });

  it('generates TEXT NOT NULL for required text field', () => {
    const output = generateMigration(FIXTURE_CONFIG);
    expect(output).toContain('"title" TEXT NOT NULL');
  });

  it("generates DEFAULT 'open' for text field with default open", () => {
    const output = generateMigration(FIXTURE_CONFIG);
    expect(output).toContain('"status" TEXT DEFAULT \'open\'');
  });

  it('generates DEFAULT 0 for numeric default', () => {
    const output = generateMigration(FIXTURE_CONFIG);
    expect(output).toContain('"score" INTEGER DEFAULT 0');
  });

  it('generates plain TEXT for uuid ref field (no FK constraint in SQLite)', () => {
    const output = generateMigration(FIXTURE_CONFIG);
    // assignee_id has ref: user but no extra FK syntax needed for SQLite
    expect(output).toContain('"assignee_id" TEXT');
  });

  it('output is valid SQL (no syntax markers from YAML leak through)', () => {
    const output = generateMigration(FIXTURE_CONFIG);
    // Should not contain YAML-isms
    expect(output).not.toContain('primaryKey:');
    expect(output).not.toContain('required:');
    expect(output).not.toContain('default:');
  });
});

// ---------------------------------------------------------------------------
// Integration: init Lattice from YAML config via Lattice constructor
// ---------------------------------------------------------------------------

import { Lattice } from '../../src/lattice.js';
import { parseConfigString } from '../../src/config/parser.js';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

describe('Lattice init from parsed config', () => {
  it('registers all entities and can insert + query', async () => {
    const yaml = `
db: ./ignored.db
entities:
  project:
    fields:
      id:   { type: uuid, primaryKey: true }
      name: { type: text, required: true }
    render: default-list
    outputFile: out.md
`;
    const { tables } = parseConfigString(yaml, tmpdir());
    const db = new Lattice(':memory:');
    for (const { name, definition } of tables) {
      db.define(name, definition);
    }
    await db.init();

    await db.insert('project', { id: 'p-1', name: 'Alpha' });
    await db.insert('project', { id: 'p-2', name: 'Beta' });

    const rows = await db.query('project', { orderBy: 'id' });
    expect(rows).toHaveLength(2);
    expect(rows[0]?.name).toBe('Alpha');
    db.close();
  });
});

describe('Lattice({ config }) constructor from config string path', () => {
  it('opens correctly and exposes all declared entities', async () => {
    // Write a temp config file and verify the constructor reads it
    const { writeFileSync } = await import('node:fs');
    const configContent = `
db: ./test-data.db
entities:
  tag:
    fields:
      id:    { type: uuid, primaryKey: true }
      label: { type: text, required: true }
    render: default-json
    outputFile: tags.md
`;
    const configPath = join(tmpdir(), `lattice-test-${String(Date.now())}.yml`);
    writeFileSync(configPath, configContent, 'utf-8');

    // Point the db to :memory: by using a pre-resolved path trick:
    // parseConfigFile resolves db relative to configDir, so we override
    // with a full absolute in-memory path. Easiest: write config with
    // db pointing to a temp file (not :memory:, but valid) then delete after.
    // Instead, use parseConfigString and construct manually.
    const { parseConfigString: pcs } = await import('../../src/config/parser.js');
    const { tables } = pcs(configContent, tmpdir());
    const db2 = new Lattice(':memory:');
    for (const { name, definition } of tables) {
      db2.define(name, definition);
    }
    await db2.init();

    await db2.insert('tag', { id: 't-1', label: 'bug' });
    const rows = await db2.query('tag');
    expect(rows).toHaveLength(1);
    expect(rows[0]?.label).toBe('bug');
    db2.close();
  });
});
